spring:
  application:
    name: car_repair_register
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/evidence?currentSchema=public
    username: evidence
    password: evidence123
    hikari:
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/auth/realms/evidence
          jwk-set-uri: http://localhost/auth/realms/evidence/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 64MB
      max-request-size: 72MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        format_sql: false
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
server:
  port: 8090
  servlet:
    context-path: /api/car-repair-register
  error:
    include-message: always

management:
  server:
    port: 9090

logging:
  level:
    sk.tope.car_repair_register: debug
