name: Docker Image CI

on:
  push:
    tags: ["*"]

jobs:
  docker:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
      - name: Build docker image
        run: ./mvnw spring-boot:build-image
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Tag docker image
        run: docker tag ${{secrets.DOCKER_USER}}/car-repair-register-be:latest ${{secrets.DOCKER_USER}}/car-repair-register-be:${{github.ref_name}}
      - name: Docker push
        run: docker image push --all-tags ${{secrets.DOCKER_USER}}/car-repair-register-be
